### PR TITLE
Add function extractOldEvents to unclutter actOnTimer

### PR DESCRIPTION
**Pull request by imsodin**
As requested I refactored `actOnTimer` such that it looks more like in the beginning (slight differences are obviously still there). While it is unconventional to say `extractOldEvents()` is idempotent due to the lack of input parameters, it still is in the sense that hypothetically calling it twice at the same time would have the same effect as just calling it once. I did pass the time as an argument, as it might not be used (in case `maxFiles` is reached). However that is probably overly punctual, as it would hardly ever really be additional work and even then, it would be negligible. Should I add it as argument?

### CODE REVIEW

**Comment by plouj** [comment]
There's no need to pass time as parameter, but it's not idempotent because it modifies to datastructures which are not local to it: watcher.fsEvents and watcher.trackedDirs. How about having it take an FsEventsBatch and a map[string]FsEventsBatch and return two FsEventsBatch's (one to send on the channel and one to assign to watcher.fsEvents in actOnTimer (which would either be an empty or a reduced batch). Also, why do we only want to notify about events older than fastNotifyDelay? The whole point of actOnTimer is that when it runs we want notify about all events we know about!

**Comment by plouj** [comment]
I should clarify by saying that I'm looking for a function that is also as side-effects free as possible/reasonable in addition to being idempotent.

**Comment by imsodin** [comment]
The thing with only notifying about old events is just directly taken from syncthing-inotify. In my opinion this makes sense, as we wait `fastNotifyDelay` to aggregate events before we notify syncthing-core about them. If an event occurs just before the timer fires, it wasn't around that long. This goes into the same direction as your proposal not to notify syncthing-core directly when `maxFiles` is reached, which I think is a great idea. For me notify is not just about instant changes, even more about reducing the load by scans.

Does idempotent mean something else in programming than mathematics, where it is simply that f(f(x)) = f(x)?
So by passing this arguments it does not need to be a method on `watcher` anymore, is that the point? The problem is just, that updating `fsEvents` with these return values is easy, but to update `trackedDirs` we would need to loop over all events again.
Excuse my ignorance, I am just trying to understand what the underlying principles are so that I can follow them in the future (like command-query-separation, which this should satisfy, right?).

**Comment by plouj** [comment]
> [...] If an event occurs just before the timer fires, it wasn't around that long

This is going to introduce an artificial delay to filesystem events notifications

>  [...] For me notify is not just about instant changes, even more about reducing the load by scans.

I don't understand this. To me real-time notifications were about (near) instant changes. For example if I edit a tiny text file in a large shared directory  (eg: /home/plouj) I want that tiny change to propagate to devices in the cluster without waiting for a full rescan.

Let's just send off all known events to syncthing-core in actOnTimer. That way they won't pile up and we reduce the chance of hitting maxFiles. Otherwise we can get into a situation (after a large burst of events) where we're always playing catchup.

> [...] Does idempotent mean something else in programming than mathematics

Yes, it's just easy to confuse it with stateless functions: https://en.wikipedia.org/wiki/Idempotence#Computer_science_meaning

**Comment by imsodin** [comment]
I think I produced lots of confusion (not the least for myself) by going ahead and implementing my idea of how events should be aggregated and sent to syncthing-core (procrastinating student...), even without stating what this idea is. So I guess it would be more productive to discuss and agree on how events should be registered, buffered, aggregated and sent to syncthing-core before talking about details like stateless/idempotent/... functions (even though it's quite educational for me). I will try to write down why I handled things the way I did. My written explanations tend to become somewhat obscure, which I try to avoid - so please excuse the over-structuration of trivial stuff.

**Steps an event goes through**
 - Path cleanup: Filter invalid ones and make relative to folder root
 - Ignoring events (based on .stignore)
 - aggregation
 - buffering (with overflow threshold)
 - (delayed) sending to syncthing-core

**My goals**
 - allow configurable delay before passing events to syncthing-core (tradeoff scanning/io/cpu cost vs delay)
 - don't lose information (i.e. drop events)

**Reason for immediate aggregation**
If we receive lots of events in a short time and thus reach the threshold, we drop events. Therefore we have to scan the entire folder. However all events might have come from just one directory, so scanning all the rest is pointless. Concurrent/immediate aggregation solves this problem by merging all these events when the directory threshold is reached. This is especially important for a configurable delay before sending events to syncthing-core (i.e. `fastNotifyDelay`).

**Reason to send only "old" events?**
Because syncthing-inotify does it, but: I thought this is because the point in time when the timer fires is pretty arbitrary, so this artificial delay smooths the "event collection interval" out. However that's rubbish, the point in time is still arbitrary, just delayed.. So I don't know what the real reason for this is, we should maybe ask Zillode. However playing catch-up should never become a problem, the sending is maximally delayed by one time `shortNotifyDelay`.

I hope you bear with me and I addressed all/most fundamental things that are unclear. I am looking forward to your take on this and/or more questions/critique.

**Comment by plouj** [comment]
Most of your points/points sound reasonable.

> Reason for immediate aggregation [...]

Yeah, we can start with this.

> Reason to send only "old" events? [...]

Turns out I was actually the one who added this feature to syncthing-inotify (my memory is really bad apparently!) to deal with the case of very frequently modified files. By only sending notifications about events that we've known about for at least fastNotifyDelay we attempt to wait for frequently modified file to 'settle down', but it's really just an attempt and not perfect (https://github.com/syncthing/syncthing-inotify/issues/95).

Anyways, we can go with these approaches for now. But one big suggestion:

Let's make a new type: trackedDirectory that has a counter and a time.Duration member. and make trackedDir(ectories) a map of string -> trackedDirectory. There's absolutely no need to keep track of the children paths.

**Comment by imsodin** [comment]
> Let's make a new type: trackedDirectory that has a counter and a time.Duration member. and make trackedDir(ectories) a map of string -> trackedDirectory. There's absolutely no need to keep track of the children paths.

I need those children because in case the `maxFilesPerDir` limit is reached, we need to clean up. Meaning after adding an event for the parent directory remove all events in that directory from `fsEvents`. It would be much more costly to loop over all events in `fsEvent` and test whether they are a child of the new parent event. I don't have an idea how to handle this efficiently without childevents in `trackedDirs`.

> Reason to send only "old" events? [...]

The syncthing-inotify issue brought me to an idea, that might extend this. We could track both the time an event occurred on a specific path first (we do that already) and last. Thus we can send when the last occurrence is at least `shortNotifyDelay` old (i.e. the file settled) or when the first occurrence is too old (some new time interval. e.g. 10s). What do you think about that?

**Pull request closed without merging**
