### PR TITLE
Remove unnecessary locks

### PR DESCRIPTION
**Pull request by imsodin**
Previously I ignored that `ignores` are passed as a pointer. So the `updateIgnores` function is pointless and the lock from the `model` should be used, not a new one introduced.
The readlock in rwfolder.go should stay active until the has is done.

### CODE REVIEW

**Comment by plouj** [comment]
Good catch. But I'd rather not pass mutexes to NewFsWatcher. Let's do it similar to Model.addFolderLocked/AddFolder.

**Comment by imsodin** [comment]
I probably don't understand you: The AddFolder wraps addFolderLocked with locks, but we cannot do the same with NewFsWatcher, as we use the ignores many times in subsequent goroutinges and all this accesses should be read locked. So we need a way to lock from within fswatcher. What am I missing or getting wrong?

**Comment by imsodin** [comment]
I update the PR with another instance, where according to my reasoning the read mutex shold be kept longer. Just to be consistent. As the (ongoing) discussion suggests, I might be getting something entirely wrong about this whole RWMutex business.

**Comment by imsodin** [comment]
I am sorry for all this confusion (at least on my side).
Until now I dealt mostly with single threaded python, so no concurrency and everything is a name (so you car a lot about im-/mutability), I got completely lost in the mutex/pointer business. I think I understand now (hopefully). The mutex is there to protect access to the pointers in the model.folderIgnores map (well actually access to the map in general), not the access to the data that is behind these pointers. I wrongly assumed the second thing and thus thought that the lock has to stay as long as you access the data behind the pointer.

So now this PR removes unnecessary locks - sorry again...

EDIT: My current understanding of the purpose of the `model.fmut` RWMutex was just confirmed by calmh.

**Comment by plouj** [comment]
I've squashed this into your other commit and I've added my own on top of it that I _think_ should make it better by making a copy of the ignores (`Matcher`) object. That way we don't have to worry about it being modified after we've updated it.

**Pull request closed without merging**
