### PR TITLE
Make sure all paths are expanded (tilde, symlinks)

### PR DESCRIPTION
**Pull request by imsodin**
If a folderpath includes tildes or symlinks that creates problems with the notify library and ignoring, so this ensures all paths are expanded.

### CODE REVIEW

**Comment by plouj** [comment]
This needs a more careful look than I can offer right now. Especially because the paths must match those in the `FsWatcher.inProgress` and if I remember correctly those are relative rather than absolute.

**Comment by imsodin** [comment]
Sorry, I just adapted from syncthing-notify without actually checking whether it is necessary. The folderpath is already cleaned/expanded, so I reverted those changes.
Checking the paths coming from the notify library might still be a good idea, as we do not control in which format they come in (I guess it is also cleaned and expanded, but still).
However there should be no problem with relative vs absolute paths. After the absolute path from the notify library is checked it is made relative to the folderPath. Internally all event paths are relative.

**Comment by plouj** [comment]
Is there a particular situation or setup that actually requires doing ExpandTilde or RealPath on the paths we get from the inotify library? I'm all for defensive programming, but I don't want to add extra code if the version of the inotify code that we're compiling against actually makes it unnecessary.

I couldn't trigger an issue by simply having something like `<folder id="jks3lj4" label="Default Folder (jks3lj4)" path="~/Sync/" type="readwrite" rescanIntervalS="60" longRescanIntervalS="10799" ignorePerms="false" autoNormalize="true">` in my syncthing config.xml. Syncthing automatically converted that to "/home/plouj/Sync" early on.

**Comment by imsodin** [comment]
On the syncthing side it is unnecessary for sure, that's why I removed it. And I think your right, it is unnecessary in general.
There is just one very remote case where it might be useful: If notify follows symlinks when installing watches it would be useful to resolve these (then the real path would be checked whether it is in the current folder). If it is not resolved we inform about a path that is not understood by syncthing (it does not follow symlinks ever, right?). It is not clear from the documentation of notify whether it follows symlinks or not. I guess not as it is mentioned that the base path gets resolved to the real path, but I do not know.

**Pull request closed without merging**
